### ISSUE TITLE
When celery task call a function in django-app which uses django-redis, raise NOAUTH error.

### ISSUE THREAD

**Issue by addbook** [niwinz/django-redis#126]
the authenticate uri settings
```
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://:xxxxxxxx@127.0.0.1:6379/0",
        "TIMEOUT": 300,
        "KEY_PREFIX": "default",
        "VERSION": 1,
        "OPTIONS": {
            'SOCKET_TIMEOUT': 5
        }
    }
}
``` 

exception
```
[2015-04-21 11:01:25,192: ERROR/MainProcess] Task members.new_share_like[cae1392a-9bcc-466a-a931-94096a8f70b4] raised unexpected: ResponseError('NOAUTH Authentication required.',)
Traceback (most recent call last):
  File "/opt/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/lib/python2.7/site-packages/celery/app/trace.py", line 437, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/server/src/members/tasks.py", line 27, in process_new_share_like
    members.service.inc_like_shares_count(publisher_id)
  File "/opt/server/src/members/service.py", line 989, in inc_counter
    update_counter(member_id, **{key: cnt})
  File "/opt/server/src/members/service.py", line 980, in update_counter
    members.caches.set_member_counter_from_cache(member_id, json_data)
  File "/opt/server/src/members/caches.py", line 17, in set_member_counter_from_cache
    conn.hmset(key, json_data)
  File "/opt/lib/python2.7/site-packages/redis/client.py", line 1872, in hmset
    return self.execute_command('HMSET', name, *items)
  File "/opt/lib/python2.7/site-packages/redis/client.py", line 564, in execute_command
    connection.send_command(*args)
  File "/opt/lib/python2.7/site-packages/redis/connection.py", line 556, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/opt/lib/python2.7/site-packages/redis/connection.py", line 532, in send_packed_command
    self.connect()
  File "/opt/lib/python2.7/site-packages/redis/connection.py", line 440, in connect
    self.on_connect()
  File "/opt/lib/python2.7/site-packages/redis/connection.py", line 514, in on_connect
    if nativestr(self.read_response()) != 'OK':
  File "/opt/lib/python2.7/site-packages/redis/connection.py", line 574, in read_response
    raise response
ResponseError: NOAUTH Authentication required.
```

**Comment by niwibe** [comment]
Maybe is related to the bug on redis-py parsing some kind of passwords... see #114

**Comment by niwinz** [comment]
Have you checked it to connect to other redis server with other kind of credentials, is for discard the previously mentioned issue.

**Comment by addbook** [comment]
Our redis-server-port has been limited for specified ip,  for django-redis can visit redis-server without auth.

**Comment by niwinz** [comment]
I'm clearly can't reproduce this issue :(

**Comment by niwinz** [comment]
This is not reproducible, so I can't maintain this bug open forever.
If you found more relevant details for reproduce and fix it, let me know! Thanks.
