### ISSUE TITLE
compression import error

### ISSUE THREAD

**Issue by osarabia** [niwinz/django-redis#180]
I am getting this error related with compressions  at the moment of set a key

(InteractiveConsole)
>>> from django.core.cache import cache
>>> cache.set("foo","value",9000)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/python/lib/python2.7/site-packages/django_redis-4.3.0-py2.7.egg/django_redis/cache.py", line 32, in _decorator
    return method(self, *args, **kwargs)
  File "/usr/local/python/lib/python2.7/site-packages/django_redis-4.3.0-py2.7.egg/django_redis/cache.py", line 67, in set
    return self.client.set(*args, **kwargs)
  File "/usr/local/python/lib/python2.7/site-packages/django_redis-4.3.0-py2.7.egg/django_redis/cache.py", line 62, in client
    self._client = self._client_cls(self._server, self._params, self)
  File "/usr/local/python/lib/python2.7/site-packages/django_redis-4.3.0-py2.7.egg/django_redis/client/default.py", line 63, in __init__
    compressor_cls = load_class(compressor_path)
  File "/usr/local/python/lib/python2.7/site-packages/django_redis-4.3.0-py2.7.egg/django_redis/util.py", line 64, in load_class
    mod = import_module(mod_name)
  File "/usr/local/python/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named compressors.identity

**Comment by niwinz** [comment]
Have you installed django-redis from git repository?

**Comment by niwinz** [comment]
I'm saying that because the 4.3.0 does not have anything related to new compressors... they are comming on the 4.4.0

**Comment by osarabia** [comment]
Yes I am installing it from git repository

**Comment by niwinz** [comment]
Ok, with cd2ba1e commit introduced in master it should be fixed.
