### ISSUE TITLE
invalid literal for int() with base 10

### ISSUE THREAD

**Issue by nikunjbadjatya** [niwinz/django-redis#203]
Using django_redis 4.4.3 with django 1.6.3 with redis-server 3.0.0 and python 2.7.6 on ubuntu 14.04.
My LOCATION comes to be like this: 
'redis://:qwerty#asdfg@MYHOST:6379/3'

```
**`Traceback (most recent call last):
  File "/opt/portal/.venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 90, in get_response
    response = middleware_method(request)
  File "./apps/auth/middleware.py", line 28, in process_request
    user = auth.authenticate(userinfo=request.COOKIES.get('user_id', None))
  File "/opt/portal/.venv/local/lib/python2.7/site-packages/django/contrib/auth/__init__.py", line 49, in authenticate
    user = backend.authenticate(**credentials)
  File "./apps/auth/backends.py", line 114, in authenticate
    userinfo = cache.get('iam_user_%s' % userinfo)
  File "/opt/portal/.venv/local/lib/python2.7/site-packages/django_redis/cache.py", line 32, in _decorator
    return method(self, *args, **kwargs)
  File "/opt/portal/.venv/local/lib/python2.7/site-packages/django_redis/cache.py", line 81, in get
    client=client)
  File "/opt/portal/.venv/local/lib/python2.7/site-packages/django_redis/client/default.py", line 199, in get
    client = self.get_client(write=False)
  File "/opt/portal/.venv/local/lib/python2.7/site-packages/django_redis/client/default.py", line 98, in get_client
    self._clients[index] = self.connect(index)
  File "/opt/portal/.venv/local/lib/python2.7/site-packages/django_redis/client/default.py", line 108, in connect
    return self.connection_factory.connect(self._server[index])
  File "/opt/portal/.venv/local/lib/python2.7/site-packages/django_redis/pool.py", line 97, in connect
    connection = self.get_connection(params)
  File "/opt/portal/.venv/local/lib/python2.7/site-packages/django_redis/pool.py", line 108, in get_connection
    pool = self.get_or_create_connection_pool(params)
  File "/opt/portal/.venv/local/lib/python2.7/site-packages/django_redis/pool.py", line 127, in get_or_create_connection_pool
    self._pools[key] = self.get_connection_pool(params)
  File "/opt/portal/.venv/local/lib/python2.7/site-packages/django_redis/pool.py", line 140, in get_connection_pool
    return self.pool_cls.from_url(**cp_params)
  File "/opt/portal/.venv/local/lib/python2.7/site-packages/redis/connection.py", line 813, in from_url
    'port': int(url.port or 6379),
  File "/usr/lib/python2.7/urlparse.py", line 113, in port
    port = int(port, 10)
ValueError: invalid literal for int() with base 10: 'qwerty'`**
```

What could be the reason for this error?

**Comment by niwinz** [comment]
Because you have host missing on the connection uri

**Comment by nikunjbadjatya** [comment]
Oh sorry. Github didnt show "<ip>".
Its actually with host. I just updated my initial query with x.x.x.x

**Comment by nikunjbadjatya** [comment]
Here is my CACHE setting:
`
{'default': {'OPTIONS': {'SOCKET_TIMEOUT': 5, 'CLIENT_CLASS': 'django_redis.client.DefaultClient'}, 'LOCATION': 'redis://:qwerty#asdf@MYHOST:6379/3', 'BACKEND': 'django_redis.cache.RedisCache'}}
`

**Comment by niwinz** [comment]
A possible issue also can be the "#" in the password, see more in #201

**Comment by niwinz** [comment]
As you can see here:

```
>>> urlparse.urlparse("http://:qwerty#test@localhost:3333/3")
ParseResult(scheme='http', netloc=':qwerty', path='', params='', query='', fragment='test@localhost:3333/3')
```

The "#" is not valid character, and the parsed url put everything after `#` (including) as fragment, leaving port, host and remaining url fields as empty.

**Comment by nikunjbadjatya** [comment]
I could actually use python redis library and use the same set of credentials.
`
Python 2.7.6 (default, Jun 22 2015, 17:58:13)
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import redis
>>> import config
>>> r = redis.StrictRedis(host=config.REDIS_HOST, password=config.REDIS_PASSWORD, port=6379, db=3)
>>> r.keys()
[':1:somekey']
>>>
`

Hm. Ok. What could be the solution for this?
Would urlencoding help?

**Comment by niwinz** [comment]
When you use redis directly you are not using the URI format for connection string. django-redis uses the URI format that redis-py exposes in order to simplify stuff and have one unique key that indicates the connection parameter.

Url encoding may help (but I don't know),  but IMHO, just use password with urlsafe character set.
