### ISSUE TITLE
why the django-redis not hset command?

### ISSUE THREAD

**Issue by yjdwbj** [niwinz/django-redis#221]
Please , when I'm use hset command and return blow error:

```
Traceback (most recent call last):
  File "/home/yjdwbj/workspace/mqtt_auth/user_manager/tests.py", line 265, in test_ErrorDataAction
    d = self.login_request(user)
  File "/home/yjdwbj/workspace/mqtt_auth/user_manager/tests.py", line 331, in login_request
    response = IotAppAuth(request)
  File "/opt/python-2710/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/yjdwbj/workspace/mqtt_auth/user_manager/views.py", line 163, in IotAppAuth
    return PreCheckRequest(request,obj,data)
  File "/home/yjdwbj/workspace/mqtt_auth/user_manager/views.py", line 111, in PreCheckRequest
    redis_pool.hset(hkey,'password',obj.key)
  File "/opt/python-2710/lib/python2.7/site-packages/django/core/cache/__init__.py", line 98, in __getattr__
    return getattr(caches[DEFAULT_CACHE_ALIAS], name)
AttributeError: 'RedisCache' object has no attribute 'hset'
```

**Comment by niwinz** [comment]
Django redis, is basically a cache backend for django and implements its interface. django cache interface has nothing with redis, so hset is not part of the main api. However, django-redis has the facility to access directly to the raw client, which can be used to have access to all redis api. Please, read more here: http://niwinz.github.io/django-redis/latest/#_raw_client_access

**Comment by peterbe** [comment]
What if I want to use hset and benefit from the serializer (msgpack) and the compressor (zlib)?
