### ISSUE TITLE
Does it work with django v1.10.4?

### ISSUE THREAD

**Issue by cosven** [niwinz/django-redis#248]
I have following config in settings.py.

```python
CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": redis_uri_list,
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient"
            }
        }
    }
```
I run the app with django shell, it just raise the `NotImplementedError`.

```python
In [6]: from django_redis import get_redis_connection

In [7]: get_redis_connection('default')
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
<ipython-input-7-cbeb96eca543> in <module>()
----> 1 get_redis_connection('default')

/Users/cosven/zhihu/wen/vaider/eggs/django_redis-4.7.0-py2.7.egg/django_redis/__init__.pyc in get_redis_connection(alias, write)
     15
     16     if not hasattr(cache, "client"):
---> 17         raise NotImplementedError("This backend does not support this feature")
     18
     19     if not hasattr(cache.client, "get_client"):

NotImplementedError: This backend does not support this feature
```

**Comment by solrates** [comment]
What happened here?  I'm having the same issue.

**Comment by marcus-campos** [comment]
I'm having the same issue.

```
Traceback (most recent call last):
  File "/Users/marcuscampos/Documents/Clientes/integration-orchestrator/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/marcuscampos/Documents/Clientes/integration-orchestrator/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/marcuscampos/Documents/Clientes/integration-orchestrator/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/marcuscampos/Documents/Clientes/integration-orchestrator/venv/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/marcuscampos/Documents/Clientes/integration-orchestrator/venv/lib/python3.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/marcuscampos/Documents/Clientes/integration-orchestrator/venv/lib/python3.7/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/Users/marcuscampos/Documents/Clientes/integration-orchestrator/venv/lib/python3.7/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/marcuscampos/Documents/Clientes/integration-orchestrator/venv/lib/python3.7/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/marcuscampos/Documents/Clientes/integration-orchestrator/apps/v1/hook/views.py", line 21, in post
    self.queue_class.dispatch(job='hook.notification')
  File "/Users/marcuscampos/Documents/Clientes/integration-orchestrator/apps/v1/queue/queue.py", line 16, in dispatch
    queue = django_rq.get_queue(queue, autocommit=True, is_async=run_async, default_timeout=360)
  File "/Users/marcuscampos/Documents/Clientes/integration-orchestrator/venv/lib/python3.7/site-packages/django_rq/queues.py", line 148, in get_queue
    connection = get_connection(name)
  File "/Users/marcuscampos/Documents/Clientes/integration-orchestrator/venv/lib/python3.7/site-packages/django_rq/queues.py", line 125, in get_connection
    return get_redis_connection(QUEUES[name], use_strict_redis)
  File "/Users/marcuscampos/Documents/Clientes/integration-orchestrator/venv/lib/python3.7/site-packages/django_rq/queues.py", line 89, in get_redis_connection
    return get_redis(config['USE_REDIS_CACHE'])
  File "/Users/marcuscampos/Documents/Clientes/integration-orchestrator/venv/lib/python3.7/site-packages/django_redis/__init__.py", line 17, in get_redis_connection
    raise NotImplementedError("This backend does not support this feature")
NotImplementedError: This backend does not support this feature
```

**Comment by cosven** [comment]
Sorry, I can't remember the situation. 
Ummm, I guess I solved it by myself last time.
