### ISSUE TITLE
Failed when running test

### ISSUE THREAD

**Issue by Karmenzind** [niwinz/django-redis#338]
When running test with `python manage.py test xxx`, I got:

```
[2018-10-12 17:09:38,856] INFO: Cleared cache. (num: 0) [apps.py:31:ready]
Creating test database for alias 'default'...
Got an error creating the test database: (1007, "Can't create database 'test_ais'; database exists")
Type 'yes' if you would like to try deleting the test database 'test_ais', or 'no' to cancel: yes
Destroying old test database for alias 'default'...
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/home/k/.venvs/ais_py36/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/k/.venvs/ais_py36/lib/python3.6/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/k/.venvs/ais_py36/lib/python3.6/site-packages/django/core/management/commands/test.py", line 29, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "/home/k/.venvs/ais_py36/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/k/.venvs/ais_py36/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/home/k/.venvs/ais_py36/lib/python3.6/site-packages/django/core/management/commands/test.py", line 62, in handle
    failures = test_runner.run_tests(test_labels)
  File "/home/k/.venvs/ais_py36/lib/python3.6/site-packages/django/test/runner.py", line 601, in run_tests
    old_config = self.setup_databases()
  File "/home/k/.venvs/ais_py36/lib/python3.6/site-packages/django/test/runner.py", line 546, in setup_databases
    self.parallel, **kwargs
  File "/home/k/.venvs/ais_py36/lib/python3.6/site-packages/django/test/utils.py", line 187, in setup_databases
    serialize=connection.settings_dict.get('TEST', {}).get('SERIALIZE', True),
  File "/home/k/.venvs/ais_py36/lib/python3.6/site-packages/django/db/backends/base/creation.py", line 79, in create_test_db
    call_command('createcachetable', database=self.connection.alias)
  File "/home/k/.venvs/ais_py36/lib/python3.6/site-packages/django/core/management/__init__.py", line 131, in call_command
    return command.execute(*args, **defaults)
  File "/home/k/.venvs/ais_py36/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/home/k/.venvs/ais_py36/lib/python3.6/site-packages/django/core/management/commands/createcachetable.py", line 43, in handle
    cache = caches[cache_alias]
  File "/home/k/.venvs/ais_py36/lib/python3.6/site-packages/django/core/cache/__init__.py", line 80, in __getitem__
    cache = _create_cache(alias)
  File "/home/k/.venvs/ais_py36/lib/python3.6/site-packages/django/core/cache/__init__.py", line 47, in _create_cache
    params = conf.copy()
AttributeError: 'str' object has no attribute 'copy'
```

I tried to debug this, and I found `_create_cache` runned twice and during the second time the corresponding variables became wierd:

```
# at /home/k/.venvs/ais_py36/lib/python3.6/site-packages/django/core/cache/__init__.py line 47
backend = {str} "KEY_PREFIX"
conf = {str} 'xxx'  # the value of KEY_PREFIX
kwargs = {dict} {}
```

Any advise?

------

My settings are:

```
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://%s" % REDIS_HOST,
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    },
    "KEY_PREFIX": CACHE_KEY_PREFIX,
    "TIMEOUT": 3600,
}

SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "default"
```

**Comment by Karmenzind** [comment]
I changed my settings to:

```python
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://%s" % REDIS_HOST,
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
        "KEY_PREFIX": CACHE_KEY_PREFIX,
        "TIMEOUT": 3600,
    },
}
```

And now `py manage.py test` works well.  I think that Django treat `KEY_PREFIX` and `TIMEOUT` as cache backends.
