### ISSUE TITLE
Error when locking while using mockredis

### ISSUE THREAD

**Issue by OskarPersson** [niwinz/django-redis#339]
I've setup `mockredis.mock_redis_client` as my `REDIS_CLIENT_CLASS` but when I use `lock()` I get the following exception:

```
Traceback (most recent call last):
  File "/Users/Oskar/git/proj/app.py", line 155, in run
    with cache.lock(lock_key, timeout=60):
  File "/Users/Oskar/.pyenv/versions/py36/lib/python3.6/site-packages/django_redis/cache.py", line 32, in _decorator
    return method(self, *args, **kwargs)
  File "/Users/Oskar/.pyenv/versions/py36/lib/python3.6/site-packages/django_redis/cache.py", line 148, in lock
    return self.client.lock(*args, **kwargs)
  File "/Users/Oskar/.pyenv/versions/py36/lib/python3.6/site-packages/django_redis/client/default.py", line 237, in lock
    blocking_timeout=blocking_timeout)
TypeError: lock() got an unexpected keyword argument 'blocking_timeout'
```

Looking at the [source for mockredis](https://github.com/locationlabs/mockredis/blob/fd4e3117066ff0c24e86ebca007853a8092e3254/mockredis/client.py#L77) we can see that it doesn't accept the `blocking_timeout` in the `lock` method but instead in the `__init__` method of the class

**Comment by niwinz** [comment]
mockredis is not oficially supported. if someone wants to have it working, I'm glad to accept patches for that, but i'm personally not using it and i don't have time for adding support to it.

In any case thanks for reporting.
