### ISSUE TITLE
AttributeError: 'LocMemCache' object has no attribute 'keys'

### ISSUE THREAD

**Issue by msterzhang** [niwinz/django-redis#357]
## My code is working fine on the window, but on the Ubuntu server, it reported an error.
```
ip = request.META.get('SERVER_NAME')
number = cache.keys(ip+":*")
```
### Operating environment
```
windows: 
django==2.0.4 
django-redis==4.9.0
django-redis-cache==1.7.1
Ubuntu:
django==2.0.4 
django-redis==4.9.0
django-redis-cache==1.7.1
```

### Complete error
`Internal Server Error: /playideo-7424/
Traceback (most recent call last):
  File "/home/zhang/wbmovie/envb/python3.5/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/zhang/wbmovie/envb/python3.5/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/zhang/wbmovie/envb/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/zhang/wbmovie/movieiews.py", line 131, in play
    result = fuck_ip(ip)
  File "/home/zhang/wbmovie/movieiews.py", line 33, in fuck_ip
    number = cache.keys(ip+":*")
  File "/home/zhang/wbmovie/envb/python3.5/site-packages/django/core/cache/__init__.py", line 99, in __getattr__
    return getattr(caches[DEFAULT_CACHE_ALIAS], name)
AttributeError: 'LocMemCache' object has no attribute 'keys'
Internal Server Error: /playideo-7424/
Traceback (most recent call last):
  File "/home/zhang/wbmovie/envb/python3.5/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/zhang/wbmovie/envb/python3.5/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/zhang/wbmovie/envb/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/zhang/wbmovie/movieiews.py", line 131, in play
    result = fuck_ip(ip)
  File "/home/zhang/wbmovie/movieiews.py", line 33, in fuck_ip
    number = cache.keys(ip+":*")
  File "/home/zhang/wbmovie/envb/python3.5/site-packages/django/core/cache/__init__.py", line 99, in __getattr__
    return getattr(caches[DEFAULT_CACHE_ALIAS], name)
AttributeError: 'LocMemCache' object has no attribute 'keys'
^C[2018-12-01 20:55:59 +0800] [26880] [INFO] Handling signal: int
[2018-12-01 20:56:00 +0800] [26885] [INFO] Worker exiting (pid: 26885)
`
### Thank you for your work

**Comment by peterbe** [comment]
You're not using django-redis in your Ubuntu server. You're using LocMemCache there which is entirely different. 

Go into your Ubuntu server and run: 

```bash
$ python manage.py shell
>>> from django.conf import settings
>>> settings.CACHES
```

Look at the output there and compare that to the same command on your Windows computer.

**Comment by msterzhang** [comment]
> 进入你的Ubuntu服务器并运行：

Thank you very much for your reminder, I made a stupid act and forgot to modify the configuration information of the settings.py file. Thank you very much, it has been resolved.

**Comment by hyperkai** [comment]
With [LocMemCache](https://docs.djangoproject.com/en/4.2/topics/cache/#local-memory-caching), you can use `keys()` as shown below:

```python
from django.core.cache import cache

cache._cache.keys()
```

But, `keys()` cannot take any arguments otherwise there is error as shown below:

```python
from django.core.cache import cache

cache._cache.keys("apple") # Error
```

> TypeError: OrderedDict.keys() takes no arguments (1 given)
